global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "cats-dogs-api"
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ["cats-dogs-api:8000"]